name: attendance_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  responsive_sizer: ^3.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.1
  intl: ^0.18.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/